on:
  push:
    branches:
      - master
  pull_request:

name: CI - basic

jobs:
  build:
    name: Build ${{ matrix.build }}

    strategy:
      matrix:
        build:
          - macos
        include:
          - build: macos
            runs-on: macos-latest
            use-cross: false
            build-in-pr: false
            # TODO: Too slow; see https://github.com/actions/runner-images/issues/1336
            timeout: 60

    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: ${{ matrix.timeout }}

    steps:
      - uses: actions/checkout@v3
        # Note: making the whole job conditional w.r.t matrix, instead of every step
        # is not supported and workarounds are very gnarly
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr

      - uses: cachix/install-nix-action@v20
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        with:
          name: fedimint
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        continue-on-error: true

      - name: Build workspace
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        run: nix build -L .#debug.workspaceBuild

      - name: Clippy workspace
        if: github.ref == 'refs/heads/master' || matrix.build-in-pr
        run: nix build -L .#debug.workspaceClippy

  notifications:
    if: ${{ always() && github.ref == 'refs/heads/master' }}
    name: "Notifications"
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    needs: [ build ]

    steps:
    - name: Discord notifications on failure                                                         
      # https://stackoverflow.com/a/74562058/134409
      if: ${{ always() && contains(needs.*.result, 'failure') }}
      # https://github.com/marketplace/actions/actions-status-discord
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        # current job is a success, but that's not what we're interested in
        status: failure
